### ISSUE TITLE
Fog animation causes high GPU load

### ISSUE THREAD

**Issue by marcoow** [simplabs/breethe-client#100]
I thought that #96 had fixed that but I'm seeing high GPU load again when going to e.g. https://breethe.app/location/101. Open Activity Monitor.app and go to Window -> GPU to get the live GPU load. I'm not sure whether we can force the animation to **not** run on the GPU but we somehow need to fix that.

**Comment by jorgelainfiesta** [comment]
My computer is quite old so sometimes it has a hard time rendering if I have several tabs with Breethe open. I suspect animating several layers of transparency is quite demanding. I'll experiment to see how far I can get optimizing the current animation. Otherwise we might have to change the fog effect for something different.

**Comment by marcoow** [comment]
> Otherwise we might have to change the fog effect for something different.

yep 😞

**Comment by marcoow** [comment]
It's not really great if we build something that's super optimized in terms of load times, file size etc. but then uses 100% of your GPU when it runs. That seams to defeat the purpose of the whole thing a bit ;)

**Comment by jorgelainfiesta** [comment]
I've been making some rough experiments by changing parameters in the fog effect. Right now we have 3 layers of 'clouds' that combine to create a more complex fog. If we keep only one layer, that reduces the GPU consumption by about 30%. 

I also discovered that running two animations in one element is quite expensive. Animating only the position or only the opacity reduces the GPU load by about 25%. 

However, after removing layers and animations, the fog doesn't look very good and still uses significant GPU resources.

I suggest that we change the effect from fog to particles. Particles should be cheaper to render because they are discreet, unlike 'gas' animations. What do you think?

**Comment by marcoow** [comment]
Yes, I guess that makes sense. I recently came across this which might be helpful: https://css-tricks.com/adding-particle-effects-to-dom-elements-with-canvas/

**Comment by jorgelainfiesta** [comment]
I am implementing an animation based on the article that you mentioned. But before tuning details I checked its performance using the GPU History graph and it turns out it uses about the same resources as the current images. Perhaps we're not focusing on the right metric or maybe animating the whole background is demanding by default?

**Comment by marcoow** [comment]
The article I posted was jus an example - we don't have to use that, I didn't really read it actually, just thought it might be an option. I guess there must be a way to animate the background somehow?

I'm not sure GPU histogram is the right metric but the fans in my iMac run at full speed when I visit the site and that certainly should not happen :)

**Comment by marcoow** [comment]
Would it be possible to use a video of smoke and set the opacity of that video according to the air quality level?

**Comment by marcoow** [comment]
There would be videos available here: https://www.videoblocks.com/videos/transparent+background+fog - we'd have to validate the approach first of course…

**Comment by marcoow** [comment]
Hm, of course we'd have to figure out how we could loop that endlessly then…

**Comment by jorgelainfiesta** [comment]
That's quite interesting, but I think it'd be too hard to make it work. Finding a video that can loop seamlessly is not as easy, and we'd somehow have to set the video blending mode with the background. 

I'm making progress rendering the particles on Canvas. I've discovered several tips to make the animations less resource intensive so I hope we can get a good result from this.
