### ISSUE TITLE
Client falls back to old data even if server has more recent data

### ISSUE THREAD

**Issue by marcoow** [simplabs/breethe-client#89]
I have data from 1.6.2018 for this location in IndexedDB: https://breethe.app/location/29. However, there is data available for this location from openaq from 4.6.2018. What happens when requesting https://breethe.app/location/29 is that the server responds with the fresh data from 4.6.2018 but then the client replaces that with the old data from 1.6.2018 apparently.

**Comment by jorgelainfiesta** [comment]
Every time the measurements are updated for a location the server provides new IDs for them. When we get the related records from Orbit, we get all the previous related records including both new and old measurements. We calculated the location date based on the oldest record found in these related records, so that resulted in erroneous data.

The error did not occur for SSR because it only has fresh data available when rendering the pages.  

I'm sending a PR in a moment that corrects this issue by selecting only the most recent records from the store for every measure.
